# Makefile for false (amiport)
TARGET      = false
SOURCES     = ported/false.c
VERSION     = 1.1
DESCRIPTION = Return false value (OpenBSD)
AUTHOR      = The Regents of the University of California

include ../common.mk

.PHONY: all clean test package compare
