# Makefile for true (amiport)
include ../common.mk

TARGET      = true
SOURCES     = ported/true.c
VERSION     = 1.1
DESCRIPTION = Return true value (OpenBSD)
AUTHOR      = The Regents of the University of California

.PHONY: all clean test package compare
