# Makefile for jot (amiport)
include ../common.mk

TARGET      = jot
SOURCES     = ported/jot.c
VERSION     = 1.56
DESCRIPTION = Print sequential or random data (OpenBSD)
AUTHOR      = The Regents of the University of California

LDFLAGS += -lm

.PHONY: all clean test package compare
