# Makefile for getopt (amiport)
TARGET      = getopt
SOURCES     = ported/getopt.c
VERSION     = 1.10
DESCRIPTION = Parse command options (OpenBSD)
AUTHOR      = Henry Spencer

include ../common.mk

.PHONY: all clean test package compare
