/* pathdef.c — generated by amiport Makefile */
#include "vim.h"
char_u *default_vim_dir = (char_u *)"S:vim";
char_u *default_vimruntime_dir = (char_u *)"S:vim/runtime";
char_u *all_cflags = (char_u *)"m68k-amigaos-gcc -Os -noixemul -m68020 -std=gnu99 -Wall -Wno-attributes -I../../lib/posix-shim/include -Iported -Iported/proto -DFEAT_NORMAL -DAMIGA -DNO_ARP -DUSE_TMPNAM -DNEW_SHELLSIZE -DWORDS_BIGENDIAN -DHAVE_STDARG_H -DHAVE_TGETENT -DHAVE_TERMCAP -DHAVE_ERRNO_H";
char_u *all_lflags = (char_u *)"-noixemul -m68020 -L../../lib/posix-shim -lamiport -lm";
char_u *compiled_user = (char_u *)"amiport";
char_u *compiled_sys = (char_u *)"AmigaOS 3.x";
