# Makefile for which (amiport)
include ../common.mk

TARGET      = which
SOURCES     = ported/which.c
VERSION     = 1.27
DESCRIPTION = Locate a program file (OpenBSD)
AUTHOR      = Todd C. Miller

.PHONY: all clean test package compare
