# Makefile for which (amiport)

TARGET      = which
SOURCES     = ported/which.c
VERSION     = 1.27
REVISION    = 1
DESCRIPTION = Locate a program file (OpenBSD)
AUTHOR      = Todd C. Miller

include ../common.mk

.PHONY: all clean test package compare
