# Makefile for unexpand (amiport)
TARGET      = unexpand
SOURCES     = ported/unexpand.c
VERSION     = 1.13
DESCRIPTION = Convert spaces to tabs (OpenBSD)
AUTHOR      = The Regents of the University of California

include ../common.mk

.PHONY: all clean test package compare
