# Makefile for col (amiport)
TARGET      = col
SOURCES     = ported/col.c
VERSION     = 1.20
DESCRIPTION = Filter reverse line feeds (OpenBSD)
AUTHOR      = The Regents of the University of California

include ../common.mk

.PHONY: all clean test package compare
