# Makefile for colrm (amiport)
TARGET      = colrm
SOURCES     = ported/colrm.c
VERSION     = 1.14
DESCRIPTION = Remove columns from lines (OpenBSD)
AUTHOR      = The Regents of the University of California

include ../common.mk

.PHONY: all clean test package compare
