# Makefile for rmdir (amiport)
include ../common.mk

TARGET      = rmdir
SOURCES     = ported/rmdir.c
VERSION     = 1.15
REVISION    = 1
DESCRIPTION = Remove directories
AUTHOR      = University of California, Berkeley

AMINET_CAT  = util/dir

.PHONY: all clean test package compare

test: $(TARGET)
	@echo "=== Testing $(TARGET) ==="
	@echo "=== $(TARGET) tests complete ==="
