/* localoptions.h -- AmigaOS 3.x build configuration for Dropbear SSH
 *
 * PDR-013: Dropbear SSH Client for AmigaOS
 * Target: 68020+ (Vampire V2, A1200+030/040/060)
 *
 * Overrides default_options.h. Only need to set options that differ
 * from defaults -- default_options_guard.h wraps everything in #ifndef.
 */

/* === DISABLE FEATURES REQUIRING fork()/exec() === */
#define DROPBEAR_CLI_PROXYCMD 0
#define DROPBEAR_CLI_NETCAT 0
#define DROPBEAR_CLI_ASKPASS_HELPER 0
#define DROPBEAR_REEXEC 0

/* === DISABLE SERVER-SIDE FEATURES (client-only build) === */
#define DROPBEAR_SVR_MULTIUSER 0
#define DO_MOTD 0
#define DROPBEAR_DELAY_HOSTKEY 0
#define DROPBEAR_SFTPSERVER 0
#define DROPBEAR_X11FWD 0
#define DROPBEAR_SVR_LOCALTCPFWD 0
#define DROPBEAR_SVR_REMOTETCPFWD 0
#define DROPBEAR_SVR_LOCALSTREAMFWD 0
#define DROPBEAR_SVR_AGENTFWD 0
#define DROPBEAR_SVR_PASSWORD_AUTH 0
#define DROPBEAR_SVR_PAM_AUTH 0
#define DROPBEAR_SVR_PUBKEY_AUTH 0
#define DROPBEAR_SVR_PUBKEY_OPTIONS 0
#define LOG_COMMANDS 0

/* === DISABLE POST-QUANTUM (saves ~43 KB, large stack arrays) === */
#define DROPBEAR_SNTRUP761 0
#define DROPBEAR_MLKEM768 0

/* === DISABLE WEAK/UNNECESSARY ALGORITHMS === */
#define DROPBEAR_3DES 0
#define DROPBEAR_ENABLE_GCM_MODE 0
#define DROPBEAR_ENABLE_CBC_MODE 0
#define DROPBEAR_SHA1_HMAC 0
#define DROPBEAR_SHA1_96_HMAC 0
#define DROPBEAR_SHA2_512_HMAC 0
#define DROPBEAR_DSS 0
#define DROPBEAR_RSA_SHA1 0
#define DROPBEAR_DH_GROUP14_SHA1 0
#define DROPBEAR_DH_GROUP16 0
#define DROPBEAR_DH_GROUP1 0
#define DROPBEAR_SK_KEYS 0

/* === CLIENT FEATURES === */
#define DROPBEAR_CLI_LOCALTCPFWD 1
#define DROPBEAR_CLI_REMOTETCPFWD 1
#define DROPBEAR_CLI_AGENTFWD 0
#define DROPBEAR_CLI_PASSWORD_AUTH 1
#define DROPBEAR_CLI_PUBKEY_AUTH 1
#define DROPBEAR_CLI_IMMEDIATE_AUTH 0
#define DROPBEAR_USER_ALGO_LIST 1
#define DROPBEAR_USE_PASSWORD_ENV 1
#define DROPBEAR_USE_SSH_CONFIG 0

/* === RECOMMENDED ALGORITHMS FOR 68K === */
#define DROPBEAR_CHACHA20POLY1305 1
#define DROPBEAR_ENABLE_CTR_MODE 1
#define DROPBEAR_AES128 1
#define DROPBEAR_AES256 1
#define DROPBEAR_SHA2_256_HMAC 1
#define DROPBEAR_ED25519 1
#define DROPBEAR_RSA 1
#define DROPBEAR_ECDSA 1
#define DROPBEAR_CURVE25519 1
#define DROPBEAR_ECDH 1
#define DROPBEAR_DH_GROUP14_SHA256 1

/* === AMIGAOS TUNING === */
#define DO_HOST_LOOKUP 0
#define DROPBEAR_SMALL_CODE 1
#define DEFAULT_RECV_WINDOW 24576
#define DEFAULT_KEEPALIVE 30
#define DEFAULT_IDLE_TIMEOUT 0

/* === AMIGAOS PATHS === */
#define DROPBEAR_DEFAULT_CLI_AUTHKEY "S:.ssh/id_dropbear"
#define DEFAULT_PATH "C:"

/* === NO ENTROPY DEVICE === */
#define DROPBEAR_USE_PRNGD 0

/* === DEBUG (disable for release) === */
#define DEBUG_TRACE 0
